/**
 * Alexvya Platform — Standard Error Taxonomy & AlexvyaApiError
 * Stage 1.4 API Specification
 */

export const ErrorCodes = {
  // Authentication & Authorization (401, 403)
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_FROZEN: 'ACCOUNT_FROZEN',
  ACCOUNT_CLOSED: 'ACCOUNT_CLOSED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TWO_MAN_RULE_REQUIRED: 'TWO_MAN_RULE_REQUIRED',


  // Request Validation & Input (400, 404, 422)
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_MONEY_AMOUNT: 'INVALID_MONEY_AMOUNT',
  INVALID_KOBO_AMOUNT: 'INVALID_KOBO_AMOUNT',
  MONEY_OVERFLOW: 'MONEY_OVERFLOW',
  ZERO_AMOUNT_NOT_ALLOWED: 'ZERO_AMOUNT_NOT_ALLOWED',
  INVALID_MSISDN: 'INVALID_MSISDN',
  INVALID_METER: 'INVALID_METER',
  INVALID_SMARTCARD: 'INVALID_SMARTCARD',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_DISABLED: 'PRODUCT_DISABLED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
  IDEMPOTENCY_REPLAY: 'IDEMPOTENCY_REPLAY',
  REQUEST_FINGERPRINT_MISMATCH: 'REQUEST_FINGERPRINT_MISMATCH',

  // Financial & Wallet (400, 402, 403, 404, 409, 422, 500)
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  NEGATIVE_BALANCE_FORBIDDEN: 'NEGATIVE_BALANCE_FORBIDDEN',
  DAILY_LIMIT_EXCEEDED: 'DAILY_LIMIT_EXCEEDED',
  MAX_BALANCE_EXCEEDED: 'MAX_BALANCE_EXCEEDED',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
  DUPLICATE_REFUND: 'DUPLICATE_REFUND',
  REFUND_AMOUNT_INVALID: 'REFUND_AMOUNT_INVALID',
  REFUND_AMOUNT_EXCEEDED: 'REFUND_AMOUNT_EXCEEDED',
  WALLET_LOCKED: 'WALLET_LOCKED',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_SUSPENDED: 'WALLET_SUSPENDED',
  WALLET_FROZEN: 'WALLET_FROZEN',
  WALLET_CLOSED: 'WALLET_CLOSED',
  WALLET_INVARIANT_VIOLATION: 'WALLET_INVARIANT_VIOLATION',
  WALLET_VERSION_INVALID: 'WALLET_VERSION_INVALID',
  INVALID_WALLET_STATE: 'INVALID_WALLET_STATE',
  BALANCE_INVARIANT_VIOLATION: 'BALANCE_INVARIANT_VIOLATION',
  LEDGER_ENTRY_NOT_FOUND: 'LEDGER_ENTRY_NOT_FOUND',
  LEDGER_ENTRY_EXISTS: 'LEDGER_ENTRY_EXISTS',
  LEDGER_INVARIANT_VIOLATION: 'LEDGER_INVARIANT_VIOLATION',
  LEDGER_BALANCE_MISMATCH: 'LEDGER_BALANCE_MISMATCH',
  INVALID_LEDGER_DIRECTION: 'INVALID_LEDGER_DIRECTION',
  INVALID_LEDGER_ENTRY: 'INVALID_LEDGER_ENTRY',
  INVALID_FINANCIAL_SNAPSHOT: 'INVALID_FINANCIAL_SNAPSHOT',
  INVALID_PROFIT_CALCULATION: 'INVALID_PROFIT_CALCULATION',
  IMMUTABLE_RECORD_MODIFICATION: 'IMMUTABLE_RECORD_MODIFICATION',
  CONFLICT: 'CONFLICT',

  // Provider & System (502, 503, 504, 500)
  NEGATIVE_MARGIN_FORBIDDEN: 'NEGATIVE_MARGIN_FORBIDDEN',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  METER_VALIDATION_FAILED: 'METER_VALIDATION_FAILED',
  SMARTCARD_VALIDATION_FAILED: 'SMARTCARD_VALIDATION_FAILED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  ORDER_ALREADY_SETTLED: 'ORDER_ALREADY_SETTLED',
  CROSS_USER_ACCESS_FORBIDDEN: 'CROSS_USER_ACCESS_FORBIDDEN',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_GATEWAY_TIMEOUT: 'PAYMENT_GATEWAY_TIMEOUT',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  CIRCUIT_BREAKER_OPEN: 'CIRCUIT_BREAKER_OPEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  TRANSACTION_UNKNOWN: 'TRANSACTION_UNKNOWN',

} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class AlexvyaApiError extends Error {
  public readonly code: ErrorCode;
  public readonly statusCode: number;
  public readonly details?: Record<string, unknown> | null;

  constructor(
    code: ErrorCode,
    message: string,
    statusCode = 400,
    details: Record<string, unknown> | null = null
  ) {
    super(message);
    this.name = 'AlexvyaApiError';
    this.code = code;
    this.statusCode = statusCode;
    this.details = details;
    Object.setPrototypeOf(this, AlexvyaApiError.prototype);
  }
}
